In [1]:
import numpy as np

In [2]:
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

In [3]:
count_neg_values = len(a[a < 0]) #count of negative values

In [4]:
print(count_neg_values)

4


In [5]:
count_of_pos_values = len(a[a > 0 ]) #count of positive values

In [6]:
print(count_of_pos_values)

5


In [7]:
count_pos_evens = len(a[(a > 0) & (a % 2 == 0)]) #count of positive even values

In [8]:
print(count_pos_evens)

3


In [9]:
new_lst = np.array([i + 3 for i in a])        # a + 3 for each value in a
new_lst

array([ 7, 13, 15, 26,  1,  2,  3,  3,  3, -3,  6, -4])

In [10]:
new_lst_plus_values = len(new_lst[new_lst > 0])    # count of new positive values

In [11]:
print(new_lst_plus_values)

10


In [12]:
a

array([ 4, 10, 12, 23, -2, -1,  0,  0,  0, -6,  3, -7])

In [13]:
sq = np.where(a ,a ** 2, a) # squared values of new list

In [14]:
sq

array([ 16, 100, 144, 529,   4,   1,   0,   0,   0,  36,   9,  49])

In [17]:
mean_sq = sq.mean()   #squared mean

In [ ]:
mean_sq

In [21]:
stdev = sq.std()          #standard deviation of squared values

In [38]:
stdev

144.0243035046516

In [ ]:
mean = 0
mean - stdev ,mean, stdev,


In [30]:
a

array([ 4, 10, 12, 23, -2, -1,  0,  0,  0, -6,  3, -7])

In [ ]:
a.mean()

In [31]:
center_a = a-a.mean()         #centered

array([  1.,   7.,   9.,  20.,  -5.,  -4.,  -3.,  -3.,  -3.,  -9.,   0.,
       -10.])

In [32]:
center_a.mean()

0.0

In [47]:
z_score = center_a / a.std()    # zscore formula

In [48]:
print(z_score)

[ 0.12403473  0.86824314  1.11631261  2.48069469 -0.62017367 -0.49613894
 -0.3721042  -0.3721042  -0.3721042  -1.11631261  0.         -1.24034735]


In [ ]:
import math as m
## Setup 1
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [ ]:
import numpy as np

In [ ]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [ ]:
# Use python's built in functionality/operators to determine the following:
# Exercise 1 - Make a variable called sum_of_a to hold the sum of all the numbers in above list

sum_1 = a[0]+ a[1]
sum_2 = a[2] + a[3]
sum_3 = a[4] + a[5]
sum_4 = a[6] + a[7]
sum_5 = a[8] + a[9]
sum_of_a = sum_1 + sum_2 + sum_3 + sum_4 + sum_5 
print(sum_of_a)# sum of a

In [ ]:
# Exercise 2 - Make a variable named min_of_a to hold the minimum of all the numbers in the above list
min_of_a = a[0]
print(min_of_a)

In [ ]:
# Exercise 3 - Make a variable named max_of_a to hold the max number of all the numbers in the above list
max_of_a = a[-1]
print(max_of_a)

In [ ]:
# Exercise 4 - Make a variable named mean_of_a to hold the average of all the numbers in the above list
mean_of_a = sum_of_a/len(a)
print(mean_of_a)

In [ ]:
# Exercise 5 - Make a variable named product_of_a to hold the product of multiplying all the numbers in the above list together
p_1 = a[0] * a[1]
p_2 = a[2] * a[3]
p_3 = a[4] * a[5]
p_4 = a[6] * a[7]
p_5 = a[8] * a[9]
product_of_a = p_1 * p_2 * p_3 * p_4 * p_5 
        
print(product_of_a)

In [ ]:
# Exercise 6 - Make a variable named squares_of_a. It should hold each number in a squared like [1, 4, 9, 16, 25...]
squares_of_a = np.square(a)

In [ ]:
print(squares_of_a)

In [ ]:
odds_in_a =a[a % 2 !=0]
odds_in_a

In [ ]:
evens_in_a = a[a % 2 ==0]
evens_in_a

In [ ]:
b = np.array([[3, 4, 5], [6, 7, 8]])

In [ ]:
sum_of_b = b.sum()
sum_of_b

In [ ]:
min_of_b = b.min()
min_of_b

In [ ]:
mean_of_b = b.mean()
mean_of_b

In [ ]:
prod_of_b = np.prod(b)
prod_of_b

In [ ]:
square_of_b = np.square(b)
square_of_b

In [ ]:
odds_in_b = b[b % 2 !=0]
odds_in_b

In [ ]:
evens_in_b = b[b % 2 == 0]
evens_in_b

In [ ]:
print(b)
print(b.shape)

In [ ]:
np.reshape(b, (6,1))

In [ ]:
np.reshape(b, (6,-1))

In [ ]:
c = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
c = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [ ]:
c.min()

In [ ]:
c.max()

In [ ]:
c.sum()


In [ ]:
np.prod(c)

In [ ]:
c.min(), c.max(), c.sum(), np.prod(c)

In [ ]:
np.std(c)

In [ ]:
np.var(c)

In [ ]:
print(c.shape)

In [ ]:
transposed_results = np.transpose(c)
transposed_results

In [ ]:
print(transposed_results.shape)

In [ ]:
np.dot(c,c)

In [ ]:
(c*c.transpose().prod())

In [ ]:
d = [[90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]]

In [ ]:
d = np.array(d)

In [ ]:
np.sin(d)

In [ ]:
np.cos(d)

In [ ]:
np.tan(d)

In [ ]:
d[d<0]

In [ ]:
d[d>0]

In [ ]:
np.unique(d).shape[0]

In [ ]:
print(d.shape)

In [ ]:
transpose_d = np.transpose(d)
transpose_d

In [ ]:
print(transpose_d.shape)

In [ ]:
np.reshape(d, (9,2))